### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by kyentei** [Prior99/mopidy-subidy#1]
When I try connecting to my subsonic server, I get the following error whilst starting mopidy:
```
ERROR    Got un-handled exception from SubidyBackend
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 237, in _actor_error_handling
    yield
  File "/usr/lib/python2.7/site-packages/mopidy/commands.py", line 385, in start_backends
    config=config, audio=audio).proxy()
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 93, in start
    obj = cls(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/mopidy_subidy/backend.py", line 15, in __init__
    self.playlists = playlists.SubidyPlaylistsProvider(backend=self)
  File "/usr/lib/python2.7/site-packages/mopidy_subidy/playlists.py", line 12, in __init__
    self.refresh()
  File "/usr/lib/python2.7/site-packages/mopidy_subidy/playlists.py", line 32, in refresh
    self.playlists = self.subsonic_api.get_playlists_as_refs()
  File "/usr/lib/python2.7/site-packages/mopidy_subidy/subsonic_api.py", line 137, in get_playlists_as_refs
    return [self.raw_playlist_to_ref(playlist) for playlist in self.get_raw_playlists()]
TypeError: 'NoneType' object is not iterable

```

Configuration looks as follows:
```
[subidy]
enabled = true
url = https://m.kunix.org/
username = username
password = password
```

I installed this package using modipy-subidy from the AUR on Arch

**Comment by Prior99** [comment]
I will have a look at it as soon as possible. Could you check if you have any playlists in your subsonic? And if not, try to create one and see if it still happens and report back?

**Comment by Prior99** [comment]
Thank you fot reporting. This should be fixed in b1fa8920. I will do a bit of testing and update the package in the Aur later. Could you confirm the issue is fixed and either close the issue or paste a new Stacktrace then?

**Comment by kyentei** [comment]
Connecting to Subsonic now works! I indeed had no playlists defined.

However, when I try to play a song, I get an error:
```
Nov 02 10:28:37 zen mopidy[5820]: WARNING  Could not find a application/xml decoder to handle media.
Nov 02 10:28:37 zen mopidy[5820]: WARNING  GStreamer warning: gst-stream-error-quark: No decoder available for type 'application/xml'. (6)
Nov 02 10:28:37 zen mopidy[5820]: ERROR    GStreamer error: gst-core-error-quark: Your GStreamer installation is missing a plug-in. (12)
```

Obviously there's a dependency missing now. I'm trying to figure out which one, but perhaps it should be added as a dependency to the AUR package.

**Comment by Prior99** [comment]
I will take a look at it as soon as I am home. Though I am working late today.

If you'd like, I will happily accept your Pullrequest and add you as a collaborator.

**Comment by kyentei** [comment]
Cheers! :-) My python skills aren't good enough to assist you in fixing this, I'm afraid. I'll happily contribute with bughunting though.

**Comment by Prior99** [comment]
I don't think any gstreamer plugins need to be installed. "Playing"  XML files sounds kind of wrong. I think the problem is rather that the subsonic API returns a XML where mopidy expects a media stream.

**Comment by Prior99** [comment]
Can you play the exact same audio file via the subsonic web interface? Maybe the file is broken and an error is returned.

**Comment by kyentei** [comment]
The issue persists on every song I play. I can play them just fine via the web interface.

**Comment by Prior99** [comment]
I just tested it: Subsonic answers with an XML document when an error occured in getting the stream via the REST api. It could be possible that this is the problem you are facing. I will try adding a check for this and logging an error instead of trying to play the XML.

However, this will not solve your issue. For further debugging what is wrong there I need to know what exactly the api responds when requesting the stream. In order to do so could you do the following?

1. Get the ids of random songs by calling: ```http://SUBSONIC-URL/rest/getRandomSongs.view?u=USER&p=PASSWORD&v=1.14&c=test``` This will give you an XML response containing some random songs.
2. Pick any song which does not work from the Subidy-Plugin (Which I assume are all? But please double-check) and use the id in the following call: ```http://SUBSONIC-URL/rest/stream.view?id=SONG-ID&u=USER&p=PASSWORD&c=test&v=1.14```
3. If subsonic does not answer with a media-file/binary which can be played back by any player (vlc, mpv, ...), but with an XML document, please paste it here.

If you have any issues or need any help, please ask.

And thank you again for helping me fixing this.

**Comment by kyentei** [comment]
I've tried your steps and been able to successfully play a song via the browser. Using your step2 URL, I get a proper audio stream:
```bash
zen ~ $ curl https://m.kunix.org/rest/stream.view\?id\=39513\&u\=USERNAME\&p\=PASSWORD\&c\=test\&v\=1.14 > test.file
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.5M    0 12.5M    0     0  1232k      0 --:--:--  0:00:10 --:--:-- 1371k
zen ~ $ file test.file
test.file: Audio file with ID3 version 2.4.0, contains: MPEG ADTS, layer III, v1, 320 kbps, 44.1 kHz, JntStereo
```

Could this be due to the fact that subsonic is running via a ProxyPass in Apache? I highly doubt it, since I get a proper stream from requesting the URL. Playing the song via mopidy still returns the same error (I'm using Ario as a GTK frontend to MPD)

**Comment by Prior99** [comment]
I think for some reason your subsonic or apache answer with an XML document instead of the correct media file. I will add debug-level logging to the function called by mopidy when retrieving the stream, logging the url (without the password or username) to further help you (or other people dealing with the same issue) track down what exact URL is called. 

I don't think this has anything to do with which MPD client you are using ;)

**Comment by kyentei** [comment]
Cheers! I'll report back when I have logging available. I can also try using nginx rather than Apache, but I just think it's odd that the same requests in curl don't get an XML response.

**Comment by Prior99** [comment]
I published a new version (0.2.3) to the AUR. This contains a debug message logged with the URL everytime a song is played back. To enable this, you need to start mopidy with ```-v```, e.g.: ```mopidy --config /etc/mopidy/mopidy.conf -v```.

Also depending on your plugins the log will probably be pretty messy. I recommend using ```grep``` to find the line you are looking for. Try something like ```mopidy --config mopidy.conf -v  2>&1 | grep 'Loading song'```.

Then try the URL in the browser (with your username and password replacing the ******).

**Comment by kyentei** [comment]
Cheers! Fixed the issue. Going to the URL in the browser reported "Missing Parameter" in XML. Using another account, however, worked flawlessly.

My password was too complex (apparently some characters are not allowed in the URL), resulting in an error. Bad, bad subsonic.

**Comment by Prior99** [comment]
Hm. I am not sure if this might not be an issue with the subidy plugin not escaping passwords properly. Maybe i should add url encoding. However, this would be a different issue.

Thank you for your time.
