### ISSUE TITLE
WARNING  Connecting to subsonic failed when loading list of rootdirs

### ISSUE THREAD

**Issue by gerroon** [Prior99/mopidy-subidy#23]
Hi

I am trying to use it with airsonic, and getting bunch of errors like

WARNING  Connecting to subsonic failed when searching.
WARNING  Connecting to subsonic failed when loading list of artists.

Is anyone able to connect to Airsonic sucessfully?

I am using it on Debian Testing, Mopidy 2.1.0 against Airsonic https://github.com/airsonic/airsonic/

**Comment by Prior99** [comment]
I am running this plugin against a current Airsonic version and am not experiencing such problems.

Perhaps Logs from Airsonic or any intermediate reverse proxies such as Nginx or Apache2 could help to identify the problem.

**Comment by Prior99** [comment]
Sure:

```
[subidy]
enabled = true
url = https://subdomain.mydomain.tld/
username = thisisnotmyrealusername
password = thisisnotmyrealpassword
```

**Comment by Prior99** [comment]
The Airsonic runs behind an nginx with a configuration like this:

```
upstream subsonic-prior {
    server localhost:4041 fail_timeout=0;
}

server {
    listen                          [::]:80;
    listen                          80;
    listen                          443 ssl;
    listen                          [::]:443 ssl;
    server_name                     subdomain.mydomain.tld;

    ssl_certificate                 /path/to/fullchain.pem;
    ssl_certificate_key             /path/to/privkey.pem;
    ssl_trusted_certificate         /path/to/chain.pem;
    [ ... ]

    client_max_body_size            4g;

    access_log                      /path/to/access.log;
    error_log                       /path/to/error.log;

    location / {
        proxy_set_header            Host subdomain.mydomain.tld;
        proxy_set_header            X-Forwarded-Proto https;
        proxy_pass                  http://subsonic-prior/;
    }
}
```

The Airsonic itself is the one from Dockerhub [airsonic/airsonic:latest](https://hub.docker.com/r/airsonic/airsonic/).

**Comment by gerroon** [comment]
Hi

Thanks for posting it. I need to put a port (8080) since this is a local running instance.  What would be the format for the default airsonic url (http:localhost:8080) ?

Do you think this is the issue for me?> I do not want to run it behind  web server.

**Comment by Prior99** [comment]
Hey: `url = http://localhost:8080/` should work just fine.

**Comment by gerroon** [comment]
@Prior99 

Works now, thanks!
