### ISSUE TITLE
This doesn't work on Mopidy 3.0.1

### ISSUE THREAD

**Issue by AryToNeX** [Prior99/mopidy-subidy#28]
Latest Mopidy version dropped Python 2.7 completely. Please, update this extension to support it; it would be much needed!

**Comment by aagallag** [comment]
This PR updates subidy for Python 3: https://github.com/Prior99/mopidy-subidy/pull/29

**Comment by AryToNeX** [comment]
@aagallag thanks for that PR. Will you maintain the software in the near future?

**Comment by Prior99** [comment]
With the PR merged (thanks) I guess this can be closed.
I would be happy to add collaborators on this.
