### ISSUE TITLE
Not all albums are listed under "Subsonic -> Albums" virtual folder

### ISSUE THREAD

**Issue by AryToNeX** [Prior99/mopidy-subidy#30]
I have a whole lot of albums stored on my Subsonic server. When I try to list them via Subidy, I can get to the letter H (sorted alphabetically); not beyond that letter. I know for sure I have albums with names starting with alphabetical letters beyond H, like M (like the Metal Gear Solid original soundtrack).

Bonus issue, album arts are not displayed at all when navigating "Subsonic -> Albums" through the Iris web frontend.

**Comment by brynedwards** [comment]
Probably because the results are limited to 500: https://github.com/Prior99/mopidy-subidy/blob/35340c5c69327ed90e784142549c024086735fd9/mopidy_subidy/subsonic_api.py#L17

**Comment by AryToNeX** [comment]
Someone should take this project and update it, by the way. I don't get why it's now featured in Mopidy's official website if it's basically dead

**Comment by Prior99** [comment]
This project is actively looking for a new maintainer. I am no longer using Mopidy or Subsonic. There is a PR for updating this project to the latest version of Python and make it compatible again. Are you available as a maintainer?

**Comment by AryToNeX** [comment]
I really don't know anything about python programming so I will pass. Can't you reach out to Mopidy developers? They're sort of maintaining some otherwise inactive extensions.

**Comment by Prior99** [comment]
This is already happening, but thanks for the hint. This project is also not unmaintained - a bugfix PR would be welcome.
