### ISSUE TITLE
Name of the package in AUR

### ISSUE THREAD

**Issue by samedamci** [Prior99/mopidy-subidy#35]
Hi
Why in AUR exists package `mopidy-subidy` which is updated and package `rofi-mpd` which is outdated? Why you have two packages with totally different names and you didn't remove previous?  I want to add own script named... `rofi-mpd` to AUR but this is little conflict.

**Comment by Prior99** [comment]
Hi,

rofi-mpd is not the same as mopidy-subidy, but I am currently not actively
maintaining both and would gladly give up maintenance for mopidy-subidy or
the name for rofi-mpd.

**Comment by samedamci** [comment]
Upstream URL for `rofi-mpd` package is pointing to this repo just as `mopidy-subidy` package. :thinking: If that were not the case, I wouldn't be writing about it. If you remove package `rofi-mpd` I will happy. 😃

**Comment by Prior99** [comment]
I disowned the package.

Am So., 31. Mai 2020 um 16:06 Uhr schrieb samedamci <
notifications@github.com>:

**Comment by samedamci** [comment]
Ok, thanks!
